name: YAML Extension

on: push

jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: pecl
          ini-values: extension=yaml.so
      - run: pecl install yaml-2.0.4
      - run: php -m
      - run: php -r "if (extension_loaded('yaml')) { echo 'OK'; exit(0); } else { exit(1); }"